//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy_Homework.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Academy_Homework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string ActionResource {
            get {
                return ResourceManager.GetString("ActionResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average Calorie.
        /// </summary>
        public static string AverageCalorieResource {
            get {
                return ResourceManager.GetString("AverageCalorieResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect to Database.
        /// </summary>
        public static string ConnectToDatabaseResource {
            get {
                return ResourceManager.GetString("ConnectToDatabaseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count Fruits.
        /// </summary>
        public static string CountFruitsResource {
            get {
                return ResourceManager.GetString("CountFruitsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count Vegetable and Fruit by Color.
        /// </summary>
        public static string CountVegetableAndFruitByColorResource {
            get {
                return ResourceManager.GetString("CountVegetableAndFruitByColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count Vegetable and Fruit by Each Color.
        /// </summary>
        public static string CountVegetableAndFruitByEachColorResource {
            get {
                return ResourceManager.GetString("CountVegetableAndFruitByEachColorResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count Vegetable.
        /// </summary>
        public static string CountVegetableResource {
            get {
                return ResourceManager.GetString("CountVegetableResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data sampling.
        /// </summary>
        public static string DataSamplingResource {
            get {
                return ResourceManager.GetString("DataSamplingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteResource {
            get {
                return ResourceManager.GetString("DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum Calorie.
        /// </summary>
        public static string MaximumCalorieResource {
            get {
                return ResourceManager.GetString("MaximumCalorieResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum Calorie.
        /// </summary>
        public static string MinimumCalorieResource {
            get {
                return ResourceManager.GetString("MinimumCalorieResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show All Colors.
        /// </summary>
        public static string ShowAllColorsResource {
            get {
                return ResourceManager.GetString("ShowAllColorsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show All Data.
        /// </summary>
        public static string ShowAllDataResource {
            get {
                return ResourceManager.GetString("ShowAllDataResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show All Names.
        /// </summary>
        public static string ShowAllNamesResource {
            get {
                return ResourceManager.GetString("ShowAllNamesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vegetable and Fruit Above Calories.
        /// </summary>
        public static string VegetableAndFruitAboveCaloriesResource {
            get {
                return ResourceManager.GetString("VegetableAndFruitAboveCaloriesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vegetable and Fruit Below Calories.
        /// </summary>
        public static string VegetableAndFruitBelowCaloriesResource {
            get {
                return ResourceManager.GetString("VegetableAndFruitBelowCaloriesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vegetable and Fruit in Range of Calories.
        /// </summary>
        public static string VegetableAndFruitInRangeCaloriesResource {
            get {
                return ResourceManager.GetString("VegetableAndFruitInRangeCaloriesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vegetable and Fruits.
        /// </summary>
        public static string VegetableAndFruitsResource {
            get {
                return ResourceManager.GetString("VegetableAndFruitsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yellow or Red Vegetable and Fruit.
        /// </summary>
        public static string YellowOrRedVegetableAndFruitResource {
            get {
                return ResourceManager.GetString("YellowOrRedVegetableAndFruitResource", resourceCulture);
            }
        }
    }
}
